### ISSUE TITLE
[Solved] ValueError: 'geodesy/sphere.pyx' doesn't match any files

### ISSUE THREAD

**Issue by harshilpatel312** [sigmaai/self-driving-golf-cart#7]
While installing the geodesy package, I get the following error:

```shell
Collecting geodesy==1.1 (from -r requirements.txt (line 16))
  Using cached https://files.pythonhosted.org/packages/a9/09/09f530aa98cea743e0b999a3a2ec13fb3e99aecfaee60ce2e1ed43f21a8d/geodesy-1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-lZieNc/geodesy/setup.py", line 38, in <module>
        ext_modules=cythonize(extensions),
      File "/home/hkpatel/.local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 967, in cythonize
        aliases=aliases)
      File "/home/hkpatel/.local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 812, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "/home/hkpatel/.local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 111, in nonempty
        raise ValueError(error_msg)
    ValueError: 'geodesy/sphere.pyx' doesn't match any files
```

Solved it by installing the package directly from the git repo:

```shell
 pip install cython numpy
 pip install git+git://github.com/xolive/geodesy.git
```

**Comment by harshilpatel312** [comment]
Sorry, the above leads to errors in during `catkin_make`.

You can solve it by installing:
`sudo apt install ros-kinetic-geodesy`
